### ISSUE TITLE
Unwanted traceback error when import test case to db unsuccessfully

### ISSUE THREAD

**Issue by ngoan1608** [test-fullautomation/python-pytestlog2db#41]
As the observation from @HolQue , below traceback error is thrown when testcase is not importing to database sucessfully.
```
Traceback (most recent call last):
  File "/opt/rfwaio/python39/install/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/rfwaio/python39/install/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/rfwaio/python39/install/lib/python3.9/site-packages/PyTestLog2DB/__main__.py", line 17, in <module>
    PyTestLog2DB()
  File "/opt/rfwaio/python39/install/lib/python3.9/site-packages/PyTestLog2DB/pytestlog2db.py", line 1248, in PyTestLog2DB
    process_suite(db, suite, _tbl_test_result_id, dConfig)
  File "/opt/rfwaio/python39/install/lib/python3.9/site-packages/PyTestLog2DB/pytestlog2db.py", line 1040, in process_suite
    test_start_time += timedelta(seconds=duration)
TypeError: unsupported type for timedelta seconds component: NoneType
```
The return of test duration is missing in this case.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
solved and released with version 0.10.0
